spring:
  profiles:
    active: dev
  datasource:
     driver-class-name: net.sourceforge.jtds.jdbc.Driver
     url: jdbc:jtds:sqlserver://127.0.0.1:1433;DatabaseName=frm
     name: sa
     password: saadmin
     type: com.alibaba.druid.pool.DruidDataSource
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,log4j
     # 初始化大小，最小，最大
     initialSize: 5
     minIdle: 1
     maxActive: 20
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUA
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
     poolPreparedStatements: true
     maxOpenPreparedStatements: 20
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     useGlobalDataSourceStat: true

#mybatis
mybatis:
  type-aliases-package: net.business.*.entity
  mapper-locations: classpath:mapper/*.xml
  not-empty: false
  identity: sqlserver

#pagehelper
pagehelper:
  helperDialect: sqlserver
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

my:
  name: forezp
  age: 12
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${my.name}